
language: minimal
dist: xenial
install: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash

script:
      - cd matlab; matlab -batch "runtestsuite"
      - cd matlab; bash <(curl -s https://codecov.io/bash)
