
clear all
disp('=================')
fprintf('TEST 002a: ')

fixed_array = ...
  struct(...
        'type','linear', ...
        'align','x', ...
        'face','up', ...
        'length', 0.01, ...
        'width',  0.01, ...
        'height', 0.01, ...
        'Nmag_per_wave', 4, ...
        'Nwaves', 1, ...
        'magn', 1, ...
        'magdir_first', 90 ...
  );

float_array = fixed_array;
float_array.face = 'down';
float_array.magdir_first = -90;

displ = [0 0 0.02];

f_total = multipoleforces(fixed_array, float_array, displ);

assert( chop(f_total(3),5)==0.13909 , 'Regression shouldn''t fail');

fprintf('passed\n')
disp('=================')


