
clear all
disp('=================')
fprintf('TEST 002b: ')

fixed_array = ...
  struct(...
        'type','linear', ...
        'align','x', ...
        'face','up', ...
        'length', 0.01, ...
        'width',  0.01, ...
        'height', 0.01, ...
        'Nmag_per_wave', 1, ...
        'Nwaves', 1, ...
        'magn', 1, ...
        'magdir_first', 90 ...
  );

float_array = fixed_array;
float_array.face = 'down';
float_array.magdir_first = -90;

displ = [0 0 0.02];

f_total = multipoleforces(fixed_array, float_array, displ);

fixed_mag = magnetdefine('type','cuboid','dim',[0.01 0.01 0.01],'magn',1,'magdir',[0  90]);
float_mag = magnetdefine('type','cuboid','dim',[0.01 0.01 0.01],'magn',1,'magdir',[0 -90]);
f_mag = magnetforces(fixed_mag,float_mag,displ);

assert( chop(f_total(3),6) == chop(f_mag(3),6) );

fprintf('passed\n')
disp('=================')

